name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        run: |
          go fmt ./...
          go vet ./...
          make build
          make test

  release:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Get version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Build binaries
        run: |
          make release
        env:
          VERSION: ${{ steps.version.outputs.version }}

      - name: Generate release notes
        id: release_notes
        run: |
          cat > release_notes.md << 'EOF'
          ## Changes in ${{ steps.version.outputs.version }}
          
          ### Downloads
          - **Linux (x86_64)**: `tfplan-commenter-linux-amd64`
          - **macOS (Intel)**: `tfplan-commenter-darwin-amd64`  
          - **macOS (Apple Silicon)**: `tfplan-commenter-darwin-arm64`
          
          ### Installation
          
          #### Quick Install
          ```bash
          curl -sSL https://raw.githubusercontent.com/akomic/go-tfplan-commenter/main/install.sh | bash
          ```
          
          #### Manual Install
          1. Download the appropriate binary for your platform
          2. Make it executable: `chmod +x tfplan-commenter-*`
          3. Move to your PATH: `mv tfplan-commenter-* /usr/local/bin/tfplan-commenter`
          
          ### Usage
          ```bash
          tfplan-commenter plan.json
          tfplan-commenter -version
          tfplan-commenter -help
          ```
          
          ### Checksums
          See `checksums.txt` for SHA256 checksums of all binaries.
          EOF

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body_path: release_notes.md
          draft: false
          prerelease: false
          files: |
            dist/tfplan-commenter-linux-amd64
            dist/tfplan-commenter-darwin-amd64
            dist/tfplan-commenter-darwin-arm64
            dist/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
